---
- hosts: all
  become: yes
  tasks:
  - name: update chache
    apt:
      update_cache: yes
  - name: install git
    apt:
      name: git
      update_cache: yes
      state: present
  - name: Install python and virtual environment
    apt:
      name: {{item}}
      update_cache: yes
      state: present
    with_items:
    - python
    - python-pip
    - pyton-virtualenv
  - name: Installation of pstgres, nginx, supervisor 
    apt:
      name: {{item}}
      update_cache: yes
      state: present
    with_items:
    - postgres
    - nginx
    - supervisor
  